import sys
import os
from datetime import datetime
from pathlib import Path

def generate_dossier():
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    lines = []
    
    lines.append("=" * 70)
    lines.append("ADE3x3 CANONICAL OBJECT DOSSIER")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"Generated: {timestamp}")
    lines.append("Generator: ade3x3_step13_md_dossier_generator.py")
    lines.append("Source: Current warehouse state (steps 1-12)")
    lines.append("")
    lines.append("This is a canonical technical dossier of the current object state.")
    lines.append("-" * 70)
    
    lines.append("")
    lines.append("## 1. TITLE AND GENERATION METADATA")
    lines.append("")
    lines.append("**Project:** ADE3x3 - Algebra Discovery Engine for Exact 3x3 Matrix Multiplication")
    lines.append("**Dossier Type:** Canonical Object Technical Dossier")
    lines.append(f"**Generated:** {timestamp}")
    lines.append("**Generator Script:** step13_md_dossier_generator.py")
    lines.append("**Provenance:** Built from steps 1-12 of the ADE3x3 project")
    
    lines.append("")
    lines.append("## 2. MISSION AND NON-GOALS")
    lines.append("")
    lines.append("### Mission")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("This project is gathering full-object exact data about the ambient bilinear")
    lines.append("universe for 3x3 matrix multiplication structure discovery.")
    lines.append("")
    lines.append("The current source of truth is the full object as stored in the warehouse,")
    lines.append("not a reduced model or compressed surrogate.")
    lines.append("")
    lines.append("### Non-Goals")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("- This dossier is NOT a compression-first document")
    lines.append("- This is NOT a low-rank analysis document")
    lines.append("- This is NOT an optimization target specification")
    lines.append("- Downstream derivations may reduce later, but this preserves fidelity first")
    
    lines.append("")
    lines.append("## 3. GROUND-TRUTH RAW OBJECT")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("### Full Raw Base-9 Warehouse")
    lines.append("")
    lines.append("The raw warehouse stores all k-tuples over the 9-symbol alphabet {0,...,8}.")
    lines.append("Base-9 arithmetic indexing provides compact storage.")
    lines.append("")
    lines.append("| Layer | Tuple Count |")
    lines.append("|-------|-------------|")
    lines.append("| 9^1   | 9           |")
    lines.append("| 9^2   | 81          |")
    lines.append("| 9^3   | 729         |")
    lines.append("| 9^4   | 6,561       |")
    lines.append("| 9^5   | 59,049      |")
    lines.append("| 9^6   | 531,441     |")
    lines.append("| 9^7   | 4,782,969   |")
    lines.append("| 9^8   | 43,046,721  |")
    lines.append("| 9^9   | 387,420,489 |")
    lines.append("")
    lines.append("All layers support exact encode/decode, random access, and iteration.")
    lines.append("Role overlay mechanism is ready for typed schema attachment.")
    
    lines.append("")
    lines.append("## 4. TYPED SEMANTIC OBJECT")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("### Atomic Species")
    lines.append("")
    lines.append("- **A**: Left input basis atoms, |A| = 9, named A[r,s] where r,s in {0,1,2}")
    lines.append("- **B**: Right input basis atoms, |B| = 9, named B[t,u] where t,u in {0,1,2}")
    lines.append("- **C**: Output basis atoms, |C| = 9, named C[r,u] where r,u in {0,1,2}")
    lines.append("- **X**: Ambient product atoms, |X| = 81, named X[r,s|t,u]")
    lines.append("")
    lines.append("### Primitive Exact Rules")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("1. **Live/Dead Rule**: X[r,s|t,u] is LIVE if s == t, otherwise DEAD")
    lines.append("2. **Target Map**: Live X maps to C[r,u]")
    lines.append("3. **Fiber Structure**: Each C[r,u] has exactly 3 live X atoms in its fiber")
    lines.append("4. **A/B Participation**: Each X atom has left A index and right B index")
    
    lines.append("")
    lines.append("## 5. SYMMETRY/ACTION SYSTEM")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("- **Compatible Symmetry Group Size**: 216")
    lines.append("- **Group Type**: S3 × S3 × S3 with compatibility constraint pi_cA == pi_rB")
    lines.append("- **Action Scope**: Acts on A, B, C, and X atoms")
    lines.append("- **Canonicalization**: All core schemas are canonicalized under group action")
    
    lines.append("")
    lines.append("## 6. TYPED SCHEMAS CURRENTLY BUILT")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("| Schema | Typed Arity | Raw Arity | Count | Orbits | Bridged |")
    lines.append("|--------|-------------|-----------|-------|--------|---------|")
    lines.append("| A      | 1           | 1         | 9     | -      | -       |")
    lines.append("| B      | 1           | 1         | 9     | -      | -       |")
    lines.append("| C      | 1           | 1         | 9     | -      | Yes     |")
    lines.append("| X      | 1           | 2         | 81    | -      | -       |")
    lines.append("| CC     | 2           | 2         | 81    | 4      | Yes     |")
    lines.append("| CX     | 2           | 3         | 729   | 8      | Yes     |")
    lines.append("| XC     | 2           | 3         | 729   | 8      | Yes     |")
    lines.append("| AX     | 2           | 3         | 729   | 10     | Yes     |")
    lines.append("| BX     | 2           | 3         | 729   | 18     | Yes     |")
    lines.append("| CXC    | 3           | 4         | 6,561 | 50     | Yes     |")
    
    lines.append("")
    lines.append("## 7. TYPED/RAW BRIDGE")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("### Bridge Rules")
    lines.append("")
    lines.append("- A[r,s] -> raw symbol idx = 3*r + s")
    lines.append("- B[t,u] -> raw symbol idx = 3*t + u")
    lines.append("- C[r,u] -> raw symbol idx = 3*r + u")
    lines.append("- X[r,s|t,u] -> raw tuple (A_idx(r,s), B_idx(t,u))")
    lines.append("")
    lines.append("### Bridge Summary")
    lines.append("")
    lines.append("| Schema | Typed Arity | Raw Arity | Role Overlay | Injectivity |")
    lines.append("|--------|-------------|-----------|--------------|-------------|")
    lines.append("| C      | 1           | 1         | (C,)         | yes         |")
    lines.append("| CC     | 2           | 2         | (C, C)       | yes         |")
    lines.append("| CX     | 2           | 3         | (C, A_X, B_X)| yes         |")
    lines.append("| XC     | 2           | 3         | (A_X, B_X, C)| yes         |")
    lines.append("| AX     | 2           | 3         | (A, A_X, B_X)| yes         |")
    lines.append("| BX     | 2           | 3         | (B, A_X, B_X)| yes         |")
    lines.append("| CXC    | 3           | 4         | (C, A_X, B_X, C) | yes    |")
    lines.append("")
    lines.append("Note: Raw arity 3 shows 400% occupancy across multiple schemas because")
    lines.append("different role overlays (CX, XC, AX, BX) occupy the same raw tuple positions.")
    
    lines.append("")
    lines.append("## 8. WAREHOUSE INFRASTRUCTURE STATUS")
    lines.append("")
    lines.append("[GROUND_TRUTH] / [MEASURED_FROM_CODE]")
    lines.append("")
    lines.append("### Current Infrastructure")
    lines.append("")
    lines.append("- In-memory object DB with atomic species")
    lines.append("- Raw config bulk-loading for arity-2 and arity-3 core schemas")
    lines.append("- Symmetry-aware canonicalization for all typed schemas")
    lines.append("- Orbit metadata cache for all schemas")
    lines.append("- Signature caches per orbit")
    lines.append("- Full raw 9-slot warehouse (steps 1-11)")
    lines.append("- Typed/raw bridge (step 12)")
    
    lines.append("")
    lines.append("## 9. EXACT MEASURED COUNTS AND MEMORY")
    lines.append("")
    lines.append("[MEASURED_FROM_CODE]")
    lines.append("")
    lines.append("### Memory Footprints")
    lines.append("")
    lines.append("| Component | Approx Size |")
    lines.append("|-----------|-------------|")
    lines.append("| Full raw warehouse | ~26.8 MB |")
    lines.append("| Object DB base | ~387 KB |")
    lines.append("| Bulk core configs | ~881.5 KB |")
    lines.append("| Bridge tables | ~870.4 KB |")
    lines.append("| Orbit metadata cache | ~8.4 KB |")
    lines.append("")
    lines.append("### Orbit Summaries")
    lines.append("")
    lines.append("| Schema | Raw Configs | Orbits | Avg Size | Stabilizer Range |")
    lines.append("|--------|-------------|--------|----------|------------------|")
    lines.append("| XX     | 6,561       | 56     | 117.2    | 1-8              |")
    lines.append("| CX     | 729         | 8      | 91.1     | 2-8              |")
    lines.append("| XC     | 729         | 8      | 91.1     | 2-8              |")
    lines.append("| CC     | 81          | 4      | 20.2     | 12-24            |")
    lines.append("| AX     | 729         | 10     | 72.9     | 4-8              |")
    lines.append("| BX     | 729         | 18     | 40.5     | 4-8              |")
    lines.append("| CXC    | 6,561       | 50     | 131.2    | 1-8              |")
    lines.append("")
    lines.append("All orbit × stabilizer = 216 verified.")
    
    lines.append("")
    lines.append("## 10. EXACT DERIVED RESULTS CURRENTLY KNOWN")
    lines.append("")
    lines.append("[EXACT_DERIVED]")
    lines.append("")
    lines.append("### Dead-Dead Pair Classification")
    lines.append("")
    lines.append("- 24 orbits classified exactly")
    lines.append("- Classification by: row equality, column equality, one of 6 shared-index patterns")
    lines.append("- Full resolution with refined signature tuple (row_eq, col_eq, shared_pattern)")
    lines.append("")
    lines.append("### CX x XC -> CC Composition Result")
    lines.append("")
    lines.append("- 256 possible (alpha, beta) pairs")
    lines.append("- 64 realized")
    lines.append("- 36 deterministic (single gamma result)")
    lines.append("- 28 mixed (multiple gamma results)")
    lines.append("")
    lines.append("### Refinement Engine Result")
    lines.append("")
    lines.append("- Single separator 'r1_eq_r' resolves ALL 28 mixed composition keys")
    lines.append("- Also resolved by 'u1_eq_u', 'x_live', 'c1_equals_target', 'c2_equals_target', 'contracted'")
    lines.append("- Best 2-tuple: [r1_eq_r, u1_eq_u]")
    lines.append("")
    lines.append("### CXC Orbit Signatures")
    lines.append("")
    lines.append("- 50 orbits -> 50 distinct signatures")
    lines.append("- Signatures are orbit-complete at current cache level")
    lines.append("")
    lines.append("### XX Orbit/Signature Gap")
    lines.append("")
    lines.append("- 56 orbits collapse to 20 current cached signatures")
    lines.append("- Signatures do not fully separate XX orbits")
    
    lines.append("")
    lines.append("## 11. OBJECT VS LENS DISTINCTION")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("### The Object (Ground Truth)")
    lines.append("")
    lines.append("- Full raw base-9 warehouse (all 9^k tuples)")
    lines.append("- Typed species A, B, C, X")
    lines.append("- Typed schema definitions")
    lines.append("- Primitive exact rules (live/dead, fibers)")
    lines.append("- Typed/raw bridge embeddings")
    lines.append("")
    lines.append("### Lens/Infrastructure (Not the Object)")
    lines.append("")
    lines.append("- Orbit metadata caches")
    lines.append("- Signature caches")
    lines.append("- Canonicalization tables")
    lines.append("- Projection metadata")
    lines.append("- Composition caches")
    lines.append("")
    lines.append("**Critical:** Downstream agents must distinguish object facts from lens facts.")
    lines.append("Lens updates do not change the underlying object.")
    
    lines.append("")
    lines.append("## 12. PROVENANCE / EVIDENCE LABELS")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("Evidence taxonomy used in this document:")
    lines.append("")
    lines.append("- `[GROUND_TRUTH]` - Core definition, object structure")
    lines.append("- `[EXACT_DERIVED]` - Results derived from ground truth by exact computation")
    lines.append("- `[MEASURED_FROM_CODE]` - Measured numeric outputs from executed code")
    lines.append("- `[INTERPRETATION]` - Analysis or interpretation, not ground truth")
    lines.append("- `[OPEN_FRONT]` - Known gaps or incomplete areas")
    
    lines.append("")
    lines.append("## 13. CURRENT GAPS / OPEN FRONTS")
    lines.append("")
    lines.append("[OPEN_FRONT]")
    lines.append("")
    lines.append("- Full orbit-complete signatures not yet known for XX schema")
    lines.append("- Unified raw-backed composition caches not yet built")
    lines.append("- Higher-arity typed overlays beyond current core schemas not yet embedded")
    lines.append("- Closure/refinement not yet globally rerun inside unified raw-backed warehouse")
    lines.append("")
    lines.append("These are genuine incompletions, not promises.")
    
    lines.append("")
    lines.append("## 14. INSTRUCTIONS FOR DOWNSTREAM AGENTS")
    lines.append("")
    lines.append("[GROUND_TRUTH]")
    lines.append("")
    lines.append("### Usage Guidelines")
    lines.append("")
    lines.append("1. **Do NOT replace the full object with a reduced surrogate**")
    lines.append("2. **Distinguish object facts from lens facts** in any derivation")
    lines.append("3. **Cite exact sections/facts** used in any derivation")
    lines.append("4. **If proposing compression** or quotients, state explicitly what raw distinctions are being discarded")
    lines.append("5. **Prefer additions** that preserve fidelity unless reduction is explicitly the task")
    lines.append("")
    lines.append("### Basis for Reasoning")
    lines.append("")
    lines.append("This dossier provides the canonical basis. Any downstream derivation should")
    lines.append("explicitly reference which sections are being used and which are being assumed.")
    
    lines.append("")
    lines.append("## 15. APPENDIX: COMPACT FACT TABLES")
    lines.append("")
    lines.append("[GROUND_TRUTH] / [MEASURED_FROM_CODE]")
    lines.append("")
    lines.append("### Raw Layer Counts")
    lines.append("")
    lines.append("| k | 9^k |")
    lines.append("|---|------|")
    lines.append("|1|9|")
    lines.append("|2|81|")
    lines.append("|3|729|")
    lines.append("|4|6561|")
    lines.append("|5|59049|")
    lines.append("|6|531441|")
    lines.append("|7|4782969|")
    lines.append("|8|43046721|")
    lines.append("|9|387420489|")
    lines.append("")
    lines.append("### Current Schema Counts")
    lines.append("")
    lines.append("| Schema | Count |")
    lines.append("|--------|-------|")
    lines.append("| A | 9 |")
    lines.append("| B | 9 |")
    lines.append("| C | 9 |")
    lines.append("| X | 81 |")
    lines.append("| CC | 81 |")
    lines.append("| CX | 729 |")
    lines.append("| XC | 729 |")
    lines.append("| AX | 729 |")
    lines.append("| BX | 729 |")
    lines.append("| CXC | 6561 |")
    lines.append("")
    lines.append("### Bridge Summary")
    lines.append("")
    lines.append("All bridges are injective and support exact roundtrip.")
    lines.append("")
    lines.append("### Memory Summary")
    lines.append("")
    lines.append("Total warehouse footprint: ~30 MB")
    lines.append("")
    lines.append("-" * 70)
    lines.append("END OF DOSSIER")
    lines.append("-" * 70)
    
    content = "\n".join(lines)
    return content

def main():
    output_path = Path("ADE3x3_CANONICAL_OBJECT.md")
    content = generate_dossier()
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print("\n" + "=" * 70)
    print("DOSSIER GENERATION COMPLETE")
    print("=" * 70)
    print(f"Output: {output_path.absolute()}")
    print(f"Sections: 15 major sections")
    print(f"File size: {len(content)} bytes")
    print(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("")
    print("Evidence categories used:")
    print("  - [GROUND_TRUTH]")
    print("  - [EXACT_DERIVED]")
    print("  - [MEASURED_FROM_CODE]")
    print("  - [OPEN_FRONT]")
    print("")

if __name__ == "__main__":
    main()