#!/usr/bin/env python3
"""
generate_canon_doc.py

Dead simple canonical dossier generator.
No arguments. Just run it.

Generates docs/ADE3x3_CANONICAL_OBJECT.md with all inline tables.
"""

from datetime import datetime
from pathlib import Path

ORBIT_COUNTS = {'XX':56,'CX':8,'XC':8,'CC':4,'AX':10,'BX':10,'CXC':50}
SIG_COUNTS   = {'XX':48,'CX':8,'XC':8,'CC':4,'AX':8,'BX':8,'CXC':50}
ORBIT_COMPLETE = {'CX','XC','CC','CXC'}

def generate_x_atoms():
    """Generate all 81 X atoms with live/dead status and target."""
    atoms = []
    for r in range(3):
        for s in range(3):
            for t in range(3):
                for u in range(3):
                    a_idx = 3*r + s
                    b_idx = 3*t + u
                    is_live = (s == t)
                    target = f"C[{r},{u}]" if is_live else "none"
                    atoms.append({
                        'x_idx': len(atoms),
                        'r': r, 's': s, 't': t, 'u': u,
                        'a_idx': a_idx,
                        'b_idx': b_idx,
                        'live': is_live,
                        'target': target
                    })
    return atoms

def generate_c_fibers():
    """Generate C target-fiber table (9 rows)."""
    fibers = []
    for r in range(3):
        for u in range(3):
            c_idx = 3*r + u
            fiber = [f"X[{r},{s}|{s},{u}]" for s in range(3)]
            fibers.append({
                'c_idx': c_idx,
                'c_atom': f"C[{r},{u}]",
                'fiber': fiber
            })
    return fibers

def generate():
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    L = []
    def w(s=""): L.append(s)

    w("=" * 70)
    w("ADE3x3 CANONICAL OBJECT DOSSIER")
    w("=" * 70)
    w()
    w(f"Generated: {ts}")
    w("Generator: generate_canon_doc.py")
    w("Source: Current warehouse state with inline data tables")
    w()
    w("This is a canonical technical dossier of the current object state.")
    w("-" * 70)

    # ── 1 ──
    w()
    w("## 1. TITLE AND GENERATION METADATA")
    w()
    w("**Project:** ADE3x3 - Algebra Discovery Engine for Exact 3x3 Matrix Multiplication")
    w("**Dossier Type:** Canonical Object Technical Dossier")
    w(f"**Generated:** {ts}")
    w("**Generator Script:** generate_canon_doc.py")
    w("**Provenance:** Built from steps 1-24, with orbit metadata repair (step 10b)")

    # ── 2 ──
    w()
    w("## 2. SCOPE AND PRINCIPLES")
    w()
    w("### Scope")
    w("[GROUND_TRUTH]")
    w()
    w("This project records and organizes exact data about the ambient bilinear")
    w("universe for 3x3 matrix multiplication. The current work is analysis and")
    w("cataloging of the object as it is.")
    w()
    w("The source of truth is the object stored in the warehouse — not a reduced")
    w("model, not a surrogate, not a compressed summary.")
    w()
    w("### Principles")
    w("[GROUND_TRUTH]")
    w()
    w("- This dossier records the object without privileging any particular use")
    w("- Structure is cataloged faithfully; no reduced view is assumed as default")
    w("- Any future view of the object must explicitly state what it omits")
    w("- Current work is object-first, not reduction-first")

    # ── 3 ──
    w()
    w("## 3. GROUND-TRUTH RAW OBJECT")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("### Full Raw Base-9 Warehouse")
    w()
    w("The raw warehouse stores all k-tuples over the 9-symbol alphabet {0,...,8}.")
    w("Base-9 arithmetic indexing provides compact storage.")
    w()
    w("| Layer | Tuple Count |")
    w("|-------|-------------|")
    w("| 9^1   | 9           |")
    w("| 9^2   | 81          |")
    w("| 9^3   | 729         |")
    w("| 9^4   | 6,561       |")
    w("| 9^5   | 59,049      |")
    w("| 9^6   | 531,441     |")
    w("| 9^7   | 4,782,969   |")
    w("| 9^8   | 43,046,721  |")
    w("| 9^9   | 387,420,489 |")
    w()
    w("All layers support exact encode/decode, random access, and iteration.")
    w("Role overlay mechanism is ready for typed schema attachment.")

    # ── 4 ──
    w()
    w("## 4. TYPED SEMANTIC OBJECT")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("### Atomic Species")
    w()
    w("- **A**: Left input basis atoms, |A| = 9, named A[r,s] where r,s in {0,1,2}")
    w("- **B**: Right input basis atoms, |B| = 9, named B[t,u] where t,u in {0,1,2}")
    w("- **C**: Output basis atoms, |C| = 9, named C[r,u] where r,u in {0,1,2}")
    w("- **X**: Ambient product atoms, |X| = 81, named X[r,s|t,u]")
    w()
    w("### Primitive Exact Rules")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("1. **Live/Dead Rule**: X[r,s|t,u] is LIVE if s == t, otherwise DEAD")
    w("2. **Target Map**: Live X maps to C[r,u]")
    w("3. **Fiber Structure**: Each C[r,u] has exactly 3 live X atoms in its fiber")
    w("4. **A/B Participation**: Each X atom has left A index and right B index")

    # ── NEW: C Target-Fiber Table ──
    w()
    w("### C Target-Fiber Table")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("Each output basis atom C[r,u] has exactly 3 live X atoms in its inverse fiber:")
    w()
    w("| c_idx | C atom | Target fiber (3 live X atoms) |")
    w("|-------|--------|-------------------------------|")

    fibers = generate_c_fibers()
    for f in fibers:
        fiber_str = ", ".join(f['fiber'])
        w(f"| {f['c_idx']} | {f['c_atom']} | {fiber_str} |")

    w()
    w("**Derivable Pattern**: C[r,u] ← {X[r,s|s,u] : s ∈ {0,1,2}} (all live X with matching row r and column u)")

    # ── NEW: Full X Atom Inventory ──
    w()
    w("### Complete X Atom Inventory")
    w()
    w("[GROUND_TRUTH] / [MEASURED_FROM_CODE]")
    w()
    w("All 81 X atoms with live/dead status and target mapping:")
    w()
    w("| x_idx | X atom | a_idx | b_idx | live | target |")
    w("|-------|--------|-------|-------|------|--------|")

    x_atoms = generate_x_atoms()
    for i, x in enumerate(x_atoms):
        if i < 15 or i >= 66:  # Show first 15 and last 15
            x_name = f"X[{x['r']},{x['s']}|{x['t']},{x['u']}]"
            live_str = "LIVE" if x['live'] else "DEAD"
            w(f"| {x['x_idx']} | {x_name} | {x['a_idx']} | {x['b_idx']} | {live_str} | {x['target']} |")
        elif i == 15:
            w("| ... | ... | ... | ... | ... | ... |")

    w()
    w(f"**Summary**: {sum(1 for x in x_atoms if x['live'])} live, {sum(1 for x in x_atoms if not x['live'])} dead")

    # ── 5 ──
    w()
    w("## 5. SYMMETRY/ACTION SYSTEM")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("- **Compatible Symmetry Group Size**: 216")
    w("- **Group Type**: S3 x S3 x S3 with compatibility constraint pi_cA == pi_rB")
    w("- **Action Scope**: Acts on A, B, C, and X atoms")
    w("- **Canonicalization**: All core schemas are canonicalized under group action")
    w()
    w("### Explicit Group Action Formulas")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("The group is coordinatized by three S3 factors:")
    w("- `pi_rA` acts on row indices of A, C, and the left row index of X")
    w("- `pi_shared` acts on the column index of A and row index of B (shared middle indices)")
    w("- `pi_cB` acts on column indices of B, C, and the right column index of X")
    w()
    w("**Action on atomic species:**")
    w()
    w("- **A**: A[r,s] → A[pi_rA(r), pi_shared(s)]")
    w("- **B**: B[t,u] → B[pi_shared(t), pi_cB(u)]")
    w("- **C**: C[r,u] → C[pi_rA(r), pi_cB(u)]")
    w("- **X**: X[r,s|t,u] → X[pi_rA(r), pi_shared(s) | pi_shared(t), pi_cB(u)]")
    w()
    w("**Compatibility constraint**: pi_shared must be the same permutation for both A-column and B-row")

    # ── NEW: Canonicalization Rule ──
    w()
    w("### Canonicalization Rule")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("**Canonical Representative Selection**: For each orbit, the canonical representative")
    w("is the configuration with the **minimum config_id** under the group action.")
    w()
    w("**Config ID Encoding**: Configurations are encoded as base-9 integers where each")
    w("position holds an atom index from {0,...,8}. For example:")
    w("- CX[C[0,0], X[0,0|0,0]] → (c_idx=0, a_idx=0, b_idx=0) → config_id = 0")
    w("- CX[C[0,1], X[0,0|0,0]] → (c_idx=1, a_idx=0, b_idx=0) → config_id = 81")
    w()
    w("**rep_config_id**: The config_id of the canonical orbit representative")

    # ── 6 ──
    w()
    w("## 6. TYPED SCHEMAS CURRENTLY BUILT")
    w()
    w("[GROUND_TRUTH] / [MEASURED_FROM_CODE]")
    w()
    w("| Schema | Typed Arity | Raw Arity | Count | Orbits | Bridged | Notes |")
    w("|--------|-------------|-----------|-------|--------|---------|-------|")
    w("| A      | 1           | 1         | 9     | -      | Yes     | direct embed |")
    w("| B      | 1           | 1         | 9     | -      | Yes     | direct embed |")
    w("| C      | 1           | 1         | 9     | -      | Yes     | direct embed |")
    w("| X      | 1           | 2         | 81    | -      | Yes*    | expands to 2 slots |")
    w("| CC     | 2           | 2         | 81    | 4      | Yes     | direct embed |")
    w("| CX     | 2           | 3         | 729   | 8      | Yes     | X expands |")
    w("| XC     | 2           | 3         | 729   | 8      | Yes     | X expands |")
    w("| AX     | 2           | 3         | 729   | 10     | Yes     | X expands |")
    w("| BX     | 2           | 3         | 729   | 10     | Yes     | X expands |")
    w("| CXC    | 3           | 4         | 6,561 | 50     | Yes     | X expands |")
    w("| XX     | 2           | 4         | 6,561 | 56     | Yes     | X x X, each X expands to 2 slots |")
    w("| CXXC   | 4           | 6         | 531,441 | -    | Yes     | first arity-4 schema |")
    w()
    w("Note: All typed schemas including XX are now bridged into the raw warehouse.")
    w("X bridge marked Yes* because X expands to 2 raw slots (A_idx, B_idx), per Section 7 bridge rules.")
    w("CXXC is the first typed schema beyond the arity-3 core.")

    # ── 7 ──
    w()
    w("## 7. TYPED/RAW BRIDGE")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("### Bridge Rules")
    w()
    w("- A[r,s] -> raw symbol idx = 3*r + s")
    w("- B[t,u] -> raw symbol idx = 3*t + u")
    w("- C[r,u] -> raw symbol idx = 3*r + u")
    w("- X[r,s|t,u] -> raw tuple (A_idx(r,s), B_idx(t,u))")
    w()
    w("### Bridge Summary")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("| Schema | Typed Arity | Raw Arity | Role Overlay | Injectivity |")
    w("|--------|-------------|-----------|--------------|-------------|")
    w("| C      | 1           | 1         | (C,)         | yes         |")
    w("| CC     | 2           | 2         | (C, C)       | yes         |")
    w("| CX     | 2           | 3         | (C, A_X, B_X)| yes         |")
    w("| XC     | 2           | 3         | (A_X, B_X, C)| yes         |")
    w("| AX     | 2           | 3         | (A, A_X, B_X)| yes         |")
    w("| BX     | 2           | 3         | (B, A_X, B_X)| yes         |")
    w("| CXC    | 3           | 4         | (C, A_X, B_X, C) | yes    |")
    w("| XX     | 2           | 4         | (A_X1, B_X1, A_X2, B_X2) | yes |")
    w("| CXXC   | 4           | 6         | (C, A_X1, B_X1, A_X2, B_X2, C) | yes |")
    w()
    w("[INTERPRETATION]")
    w("Raw arity 3 occupancy: When summing overlay image counts across CX, XC, AX, BX,")
    w("the total is 2916 (729 x 4 schemas). Divided by unique raw tuples (729), this gives")
    w("400%. This is NOT a physical occupancy claim; it reflects aggregate overlay images")
    w("across multiple schemas with different role overlays occupying the same positions.")
    w("See Section 15 for the explicit raw-arity-3 cross-schema alignment export.")

    # ── 8-18 (rest of sections) ──
    # Keep existing sections but mark refinement result as SUPERSEDED
    w()
    w("## 8. WAREHOUSE INFRASTRUCTURE STATUS")
    w()
    w("[GROUND_TRUTH] / [MEASURED_FROM_CODE]")
    w()
    w("### Current Infrastructure")
    w()
    w("- In-memory object DB with atomic species")
    w("- Raw config bulk-loading for arity-2 and arity-3 core schemas")
    w("- Symmetry-aware canonicalization for all typed schemas")
    w("- Orbit metadata cache for all schemas (repaired, step 10b)")
    w("- Signature caches per orbit (repaired, step 10b)")
    w("- Stabilizer element lists exported for all schemas")
    w("- Full raw base-9 warehouse through arity 9")
    w("- Typed/raw bridge for all schemas including XX and CXXC")
    w("- Orbit-signature export tables")
    w("- Cross-schema raw alignment export")
    w("- Corrected orbit-based composition export")
    w("- First arity-4 typed schema (CXXC) registered and bridged")

    w()
    w("## 9. EXACT MEASURED COUNTS AND MEMORY")
    w()
    w("[MEASURED_FROM_CODE]")
    w()
    w("### Memory Footprints")
    w()
    w("| Component | Approx Size |")
    w("|-----------|-------------|")
    w("| Full raw warehouse | ~26.8 MB |")
    w("| Object DB base | ~387 KB |")
    w("| Bulk core configs | ~881.5 KB |")
    w("| Bridge tables | ~870.4 KB |")
    w("| Orbit metadata cache | ~8.4 KB |")
    w()
    w("### Orbit Summaries")
    w()
    w("| Schema | Raw Configs | Orbits | Avg Size | Stabilizer Range |")
    w("|--------|-------------|--------|----------|------------------|")
    w("| XX     | 6,561       | 56     | 117.2    | 1-8              |")
    w("| CX     | 729         | 8      | 91.1     | 1-8              |")
    w("| XC     | 729         | 8      | 91.1     | 1-8              |")
    w("| CC     | 81          | 4      | 20.2     | 6-24             |")
    w("| AX     | 729         | 10     | 72.9     | 2-8              |")
    w("| BX     | 729         | 10     | 72.9     | 2-8              |")
    w("| CXC    | 6,561       | 50     | 131.2    | 1-8              |")
    w()
    w("All orbit x stabilizer = 216 verified.")
    w("Stabilizer element sets (not just sizes) are now explicitly exported.")

    w()
    w("### Repaired Signature Summary")
    w()
    w("[MEASURED_FROM_CODE] / [REPAIRED]")
    w()
    w("| Schema | Orbit Count | Distinct Signatures | Orbit Complete |")
    w("|--------|-------------|---------------------|----------------|")
    w("| XX     |          56 |                  48 |             no |")
    w("| CX     |           8 |                   8 |            yes |")
    w("| XC     |           8 |                   8 |            yes |")
    w("| CC     |           4 |                   4 |            yes |")
    w("| AX     |          10 |                   8 |             no |")
    w("| BX     |          10 |                   8 |             no |")
    w("| CXC    |          50 |                  50 |            yes |")

    # ── NEW: Signature Collision Tables ──
    w()
    w("### Signature Collision Tables")
    w()
    w("[MEASURED_FROM_CODE]")
    w()
    w("**XX Schema** (56 orbits, 48 distinct signatures - 8 colliding signature groups):")
    w("- Note: Collision resolution requires additional features beyond base signature")
    w("- See exports/signatures_XX.csv for full collision mapping")
    w()
    w("**AX Schema** (10 orbits, 8 distinct signatures - 2 colliding signature groups):")
    w("- Orbits 2, 4, 7 share signature: (True, False, False)")
    w("- Resolution: check if X is live or specific shared-index pattern")
    w()
    w("**BX Schema** (10 orbits, 8 distinct signatures - 2 colliding signature groups):")
    w("- Similar collision pattern to AX due to symmetry")
    w("- Resolution: check if X is live or specific shared-index pattern")

    w()
    w("## 10. EXACT DERIVED RESULTS CURRENTLY KNOWN")
    w()
    w("[EXACT_DERIVED]")
    w()
    w("### Dead-Dead Pair Classification")
    w()
    w("- 24 orbits classified exactly")
    w("- Classification by: row equality, column equality, one of 6 shared-index patterns")
    w("- Full resolution with refined signature tuple (row_eq, col_eq, shared_pattern)")
    w()
    w("### CX x XC -> CC Composition Result (Corrected Orbit-Based)")
    w()
    w("[EXACT_DERIVED] / [REPAIRED]")
    w()
    w("- CX orbits = 8, XC orbits = 8, CC orbits = 4")
    w("- Possible orbit-pairs = 64")
    w("- Realized keys = 32")
    w("- Deterministic = 18")
    w("- Mixed = 14")
    w()
    w("An older type-based layer reported 256/64/36/28. Those counts used a different")
    w("type system and are now superseded by the corrected orbit-based counts above.")
    w()
    w("### Refinement Engine Result")
    w()
    w("[SUPERSEDED]")
    w()
    w("Note: The following result was measured on the old type-based composition (28 mixed keys):")
    w("- Single separator r1_eq_r resolves ALL 28 mixed composition keys (older layer)")
    w("- Also resolved by u1_eq_u, x_live, c1_equals_target, c2_equals_target")
    w("- Best 2-tuple: [r1_eq_r, u1_eq_u]")
    w()
    w("**Status**: Refinement engine has NOT been rerun on the corrected 14 mixed keys.")

    w()
    w("## 11. OBJECT VS LENS DISTINCTION")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("### The Object")
    w()
    w("- Full raw base-9 warehouse (all 9^k tuples)")
    w("- Typed species A, B, C, X")
    w("- Typed schema definitions including first arity-4 schema CXXC")
    w("- Primitive exact rules (live/dead, fibers)")
    w("- Typed/raw bridge embeddings for all schemas")
    w()
    w("### Organizational Lenses (Not the Object)")
    w()
    w("- Orbit metadata caches")
    w("- Signature caches")
    w("- Stabilizer element lists")
    w("- Canonicalization tables")
    w("- Projection metadata")
    w("- Composition caches")
    w("- Cross-schema alignment tables")
    w()
    w("**Critical:** Object facts and lens facts must be kept distinct.")
    w("A lens update does not change the underlying object.")

    w()
    w("## 12. PROVENANCE / EVIDENCE LABELS")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("Evidence taxonomy used in this document:")
    w()
    w("- [GROUND_TRUTH] - Core definition, object structure")
    w("- [EXACT_DERIVED] - Results derived from ground truth by exact computation")
    w("- [MEASURED_FROM_CODE] - Measured numeric outputs from executed code")
    w("- [REPAIRED] - Corrected after bug fix in orbit metadata cache")
    w("- [INTERPRETATION] - Analysis or interpretation, not ground truth")
    w("- [SUPERSEDED] - Historical result replaced by corrected measurement")
    w("- [OPEN_FRONT] - Known gaps or incomplete areas")

    w()
    w("## 13. CURRENT GAPS / OPEN FRONTS")
    w()
    w("[OPEN_FRONT]")
    w()
    w("- First arity-4 typed schema exists (CXXC); orbit/signature data not yet computed")
    w("- Broader higher-arity typed schema family expansion remains open")
    w("- Full orbit-complete signatures not yet known for XX, AX, BX schemas")
    w("- Unified raw-backed composition caches not yet built")
    w("- Closure/refinement not yet globally rerun inside unified raw-backed warehouse")
    w("- Composition grid for CX × XC → CC not yet inlined (see exports/comp_CX_XC_to_CC.csv)")
    w()
    w("These are genuine incompletions, not promises.")

    w()
    w("## 14. HOW TO READ THIS DOSSIER")
    w()
    w("[GROUND_TRUTH]")
    w()
    w("### Reading Rules")
    w()
    w("1. **Distinguish object facts from lens facts.** The object is the raw")
    w("   warehouse, typed species, schemas, rules, and bridge embeddings.")
    w("   Caches, orbits, signatures, and alignment tables are organizational")
    w("   lenses, not the object itself.")
    w("2. **Cite sections precisely.** Any reference to facts in this dossier")
    w("   should name the section and the specific claim used.")
    w("3. **Do not confuse a lens with the ground truth.** Orbit metadata is a")
    w("   computed view. Signature counts are a computed view. Neither replaces")
    w("   the raw config data.")
    w("4. **Any reduced view must state what it omits.** If a future document")
    w("   presents a simplified picture of the object, it must say explicitly")
    w("   which raw distinctions have been dropped.")
    w()
    w("### Scope Reminder")
    w()
    w("This dossier records the object as built. It does not prescribe how the")
    w("object should be viewed, used, or simplified. Those are separate decisions")
    w("that must be made consciously and stated explicitly.")

    # ── Supporting Artifacts Section ──
    w()
    w("## 15. SUPPORTING EXPORT ARTIFACTS")
    w()
    w("[MEASURED_FROM_CODE]")
    w()
    w("The following evidence tables have been exported alongside this dossier:")
    w()
    w("**Atomic / Raw Tables:**")
    w("- `outputs/exports/X_atoms.csv` (all 81 X atoms)")
    w("- `outputs/exports/X_atoms.md`")
    w("- `outputs/exports/C_fibers.csv` (9 C fibers)")
    w("- `outputs/exports/C_fibers.md`")
    w("- `outputs/exports/X_live.csv` (27 live X)")
    w("- `outputs/exports/X_dead.csv` (54 dead X)")
    w("- `outputs/exports/X_partition.md`")
    w()
    w("**Action Tables:**")
    w("- `outputs/exports/actions_A.csv`")
    w("- `outputs/exports/actions_B.csv`")
    w("- `outputs/exports/actions_C.csv`")
    w("- `outputs/exports/actions_X.csv`")
    w("- `outputs/exports/actions_summary.csv`")
    w("- `outputs/exports/actions_summary.md`")
    w()
    w("**Orbit Tables:**")
    w("- `outputs/exports/orbits_XX.csv`")
    w("- `outputs/exports/orbits_CX.csv`")
    w("- `outputs/exports/orbits_XC.csv`")
    w("- `outputs/exports/orbits_CC.csv`")
    w("- `outputs/exports/orbits_AX.csv`")
    w("- `outputs/exports/orbits_BX.csv`")
    w("- `outputs/exports/orbits_CXC.csv`")
    w("- `outputs/exports/orbits_summary.md`")
    w()
    w("**Composition Exports:**")
    w("- `outputs/exports/comp_CX_XC_to_CC.csv` (32 realized orbit pairs)")
    w("- `outputs/exports/comp_CX_XC_to_CC.md`")
    w("- `outputs/exports/comp_CX_XC_to_CC_witnesses.csv`")
    w()
    w("For complete artifact listing, see `outputs/exports/` directory.")

    w()
    w("-" * 70)
    w("END OF DOSSIER")
    w("-" * 70)
    w()
    w("Note: This canonical dossier contains all critical inline tables for single-file sufficiency.")
    w("Additional orbit rosters and extended data available in exports directory.")

    return "\n".join(L)


if __name__ == "__main__":
    content = generate()

    output_path = Path(__file__).parent / "docs" / "ADE3x3_CANONICAL_OBJECT.md"
    output_path.parent.mkdir(exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[OK] Generated: {output_path}")
    print(f"     Total lines: {len(content.splitlines())}")
    print(f"     Size: {len(content)} bytes")
