"""
F3 TENSOR RANK OF T_matmul(3x3)
================================
Exact computation over GF(3). No optimization. Pure algebra.

T_matmul[3r+s, 3s+u, 3r+u] = 1 for r,s,u in {0,1,2}, else 0.
This tensor is NATIVE to F_3: indices are F_3 elements, arithmetic is F_3.

We compute R_{F_3}(T_matmul) exactly by exhaustive search over tensor
decompositions with entries in {0, 1, 2} (mod 3).

Strategy:
  - Flatten T to a 9x81 matrix M (mode-1 unfolding)
  - rank_F3(M) gives a LOWER bound
  - Then: systematic search for rank-R decompositions over F_3
  - Use the substitution method: fix slices, compute rank of each
"""

import numpy as np
from itertools import product
import time

def build_T_matmul():
    """Build T_matmul as 9x9x9 over F_3 (stored as int mod 3)."""
    T = np.zeros((9, 9, 9), dtype=np.int8)
    for r in range(3):
        for s in range(3):
            for u in range(3):
                i, j, k = 3*r + s, 3*s + u, 3*r + u
                T[i, j, k] = 1
    return T

def gf3_rref(M_in):
    """Row-reduce matrix over GF(3). Returns (rref, rank)."""
    M = M_in.copy().astype(np.int8)
    rows, cols = M.shape
    rank = 0
    pivot_cols = []
    for c in range(cols):
        # Find pivot in column c from row 'rank' downward
        found = -1
        for r in range(rank, rows):
            if M[r, c] % 3 != 0:
                found = r
                break
        if found == -1:
            continue
        # Swap
        M[[rank, found]] = M[[found, rank]]
        # Normalize pivot row
        inv = pow(int(M[rank, c] % 3), 1, 3)  # inverse mod 3: 1->1, 2->2
        if M[rank, c] % 3 == 2:
            M[rank] = (M[rank] * 2) % 3
        # Eliminate
        for r in range(rows):
            if r != rank and M[r, c] % 3 != 0:
                factor = M[r, c] % 3
                M[r] = (M[r] - factor * M[rank]) % 3
        pivot_cols.append(c)
        rank += 1
    return M, rank, pivot_cols

def mode_unfolding(T, mode):
    """Unfold 3-tensor along given mode (0, 1, or 2)."""
    n = T.shape[mode]
    # Move the target mode to front, then flatten the rest
    T_perm = np.moveaxis(T, mode, 0)
    return T_perm.reshape(n, -1)

def gf3_matrix_rank(M):
    """Compute rank of matrix over GF(3)."""
    _, rank, _ = gf3_rref(M % 3)
    return rank

def slice_ranks(T):
    """Compute rank of each frontal slice T[i,:,:] over GF(3)."""
    ranks = []
    for i in range(T.shape[0]):
        ranks.append(gf3_matrix_rank(T[i]))
    return ranks

def multilinear_rank_f3(T):
    """Compute multilinear rank (r_A, r_B, r_C) over GF(3)."""
    M0 = mode_unfolding(T, 0)
    M1 = mode_unfolding(T, 1)
    M2 = mode_unfolding(T, 2)
    r0 = gf3_matrix_rank(M0)
    r1 = gf3_matrix_rank(M1)
    r2 = gf3_matrix_rank(M2)
    return (r0, r1, r2)

def substitution_lower_bound(T):
    """
    Strassen's substitution method over F_3.
    Fix A = e_i (standard basis), get linear map L_i: F_3^9 -> F_3^9.
    L_i(B) = T(e_i, B, -) is a 9x9 matrix over F_3.
    
    The algebra generated by {L_0, ..., L_8} in M_9(F_3) has dimension d.
    R(T) >= 2d/(s+1) - 1 where s = max chain length.
    
    But more directly: R(T) >= dim(span{L_i}) since any rank-1 term
    contributes rank <= 1 to this span.
    
    Actually: the L_i span a subspace of M_9(F_3). Each rank-1 decomposition
    term a_r (x) b_r (x) c_r contributes a_r[i] * (b_r (x) c_r) to L_i.
    So L_i = sum_r a_r[i] * (b_r c_r^T). The matrices {b_r c_r^T} span
    a space of dimension <= R. And the L_i are linear combinations.
    
    So: dim(span{L_i}) <= R. But actually L_i ARE 9x9 matrices, and
    each = sum_r alpha_{ir} * M_r where M_r = b_r c_r^T is rank-1.
    The M_r span at most R dimensions in M_9(F_3).
    So dim(span{L_0,...,L_8}) <= R.
    
    This gives: R >= dim(span{L_i}).
    """
    # Build the 9 substitution matrices L_i = T[i, :, :] 
    L = []
    for i in range(9):
        L.append(T[i].flatten())  # 81-dimensional vector
    L_mat = np.array(L, dtype=np.int8) % 3  # 9 x 81
    sub_rank = gf3_matrix_rank(L_mat)
    return sub_rank

def kruskal_lower_bound_f3(T):
    """
    Kruskal's bound over F_3:
    R(T) >= ceil((r_A + r_B + r_C - 2) / 2)
    where (r_A, r_B, r_C) is the multilinear rank.
    
    Actually Kruskal's bound for uniqueness is different.
    The basic lower bound from multilinear rank is:
    R(T) >= max(r_A, r_B, r_C)
    """
    rA, rB, rC = multilinear_rank_f3(T)
    return max(rA, rB, rC), (rA, rB, rC)

def check_rank_r_f3(T, R, max_attempts=100000, verbose=True):
    """
    Check if T has rank <= R over F_3 by sampling random decompositions.
    
    A rank-R decomposition: T = sum_{r=1}^R a_r (x) b_r (x) c_r
    where a_r, b_r, c_r in F_3^9.
    
    For small R, we can try structured approaches.
    For R=23 (known upper bound over R), check if it works over F_3.
    """
    rng = np.random.RandomState(42)
    
    for attempt in range(max_attempts):
        # Random A, B, C in F_3^{9 x R}
        A = rng.randint(0, 3, size=(9, R)).astype(np.int8)
        B = rng.randint(0, 3, size=(9, R)).astype(np.int8)
        C = rng.randint(0, 3, size=(9, R)).astype(np.int8)
        
        # Compute sum_r A[:,r] (x) B[:,r] (x) C[:,r] mod 3
        T_approx = np.zeros((9, 9, 9), dtype=np.int8)
        for r in range(R):
            T_approx += np.einsum('i,j,k->ijk', A[:, r], B[:, r], C[:, r])
        T_approx = T_approx % 3
        
        if np.array_equal(T_approx, T):
            if verbose:
                print(f"  FOUND rank-{R} decomposition at attempt {attempt}!")
            return True, (A, B, C)
    
    return False, None

def systematic_f3_rank_search(T, R_max=23):
    """
    Systematic search for F_3 tensor rank.
    
    Key insight: over F_3, there are only 3^9 = 19683 possible vectors
    in F_3^9, so the total search space for rank-R is (19683)^{3R}.
    That's intractable for large R.
    
    Better approach: use the UNFOLDING.
    
    T unfolded as 9 x 81 matrix M. rank_F3(M) = r.
    Then R(T) >= r. And R(T) <= |F_3^r - {0}| * ... (crude bound).
    
    For T_matmul: the mode-1 unfolding is 9x81, and rank = 9 (full).
    So R >= 9 trivially.
    
    The real question: can we get tighter bounds?
    
    Approach: flattening ranks.
    For each way to partition {1,2,3} into two groups,
    we get a matrix flattening. The rank of that flattening
    is a lower bound on tensor rank.
    """
    results = {}
    
    # Mode-1: 9 x 81
    M1 = mode_unfolding(T, 0)
    r1 = gf3_matrix_rank(M1)
    results['mode1_rank'] = r1
    
    # Mode-2: 9 x 81
    M2 = mode_unfolding(T, 1)
    r2 = gf3_matrix_rank(M2)
    results['mode2_rank'] = r2
    
    # Mode-3: 9 x 81
    M3 = mode_unfolding(T, 2)
    r3 = gf3_matrix_rank(M3)
    results['mode3_rank'] = r3
    
    results['multilinear_rank'] = (r1, r2, r3)
    results['flattening_lower_bound'] = max(r1, r2, r3)
    
    return results

def commutative_algebra_bound_f3(T):
    """
    Over F_3, compute the algebra A generated by the substitution matrices.
    
    L_i = T[i,:,:] is a 9x9 matrix over F_3.
    A = F_3-algebra generated by {L_0, ..., L_8}.
    
    Compute products L_i * L_j (matrix multiplication mod 3) and their span.
    dim(A) gives information about the tensor structure.
    
    Bläser bound: R >= 2*dim(A)/(chain_length+1) - 1
    """
    n = 9
    # Collect generators
    gens = []
    for i in range(n):
        gens.append(T[i].copy())  # 9x9 matrix
    
    # Start with generators
    basis_vecs = []
    for g in gens:
        basis_vecs.append(g.flatten())
    
    # Compute products L_i * L_j mod 3
    products = []
    for i in range(n):
        for j in range(n):
            prod = (gens[i] @ gens[j]) % 3
            products.append(prod.flatten())
    
    # All vectors: generators + products
    all_vecs = np.array(basis_vecs + products, dtype=np.int8) % 3
    
    # Rank of this collection = dimension of algebra (up to degree 2)
    alg_dim = gf3_matrix_rank(all_vecs)
    
    # Also compute degree-3 products
    deg3 = []
    for i in range(n):
        for j in range(n):
            for k in range(n):
                p = (gens[i] @ gens[j] @ gens[k]) % 3
                deg3.append(p.flatten())
    
    all_vecs_3 = np.array(basis_vecs + products + deg3, dtype=np.int8) % 3
    alg_dim_3 = gf3_matrix_rank(all_vecs_3)
    
    return {
        'generators_rank': gf3_matrix_rank(np.array(basis_vecs, dtype=np.int8) % 3),
        'algebra_dim_deg2': alg_dim,
        'algebra_dim_deg3': alg_dim_3,
    }

def strassen_equations_f3(T):
    """
    Check Strassen's equations (commutation conditions) over F_3.
    
    For T = T_matmul, the substitution matrices satisfy:
    L_i * L_j = delta_{s(i), r(j)} * L_{3*r(i) + u(j)}
    where i = 3r+s, j = 3s'+u.
    
    These are the matrix unit relations. Over F_3, check which 
    of these hold and which don't (they all should — this is exact).
    """
    n = 9
    L = [T[i].copy() for i in range(n)]
    
    # Check L_i * L_j = expected
    violations = 0
    total = 0
    for i in range(n):
        ri, si = divmod(i, 3)
        for j in range(n):
            sj, uj = divmod(j, 3)
            total += 1
            prod = (L[i] @ L[j]) % 3
            if si == sj:
                # Should equal L_{3*ri + uj}
                expected_idx = 3 * ri + uj
                expected = L[expected_idx]
                if not np.array_equal(prod % 3, expected % 3):
                    violations += 1
            else:
                # Should be zero
                if np.any(prod % 3 != 0):
                    violations += 1
    
    return {'total_relations': total, 'violations': violations}


def f3_rank_via_greedy_peeling(T, verbose=True):
    """
    Greedy approach: repeatedly find and subtract rank-1 terms over F_3.
    
    At each step, find a, b, c in F_3^9 such that a (x) b (x) c 
    matches T on as many nonzero positions as possible, subtract, repeat.
    
    This gives an UPPER bound on F_3 rank.
    """
    T_work = T.copy()
    rank = 0
    terms = []
    
    while np.any(T_work % 3 != 0):
        best_score = 0
        best_abc = None
        
        # For each nonzero entry, try the rank-1 term that hits it
        nz = np.argwhere(T_work % 3 != 0)
        if len(nz) == 0:
            break
            
        # Try basis vectors and structured vectors
        # Over F_3, vectors have entries in {0, 1, 2}
        # For efficiency, try all pairs of nonzero entries to define a,b,c
        
        # Strategy: for each nonzero position (i,j,k), try a=e_i, b=e_j, c=e_k
        # scaled by T[i,j,k]
        for idx in range(min(len(nz), 200)):  # sample
            i, j, k = nz[idx]
            val = T_work[i, j, k] % 3
            if val == 0:
                continue
            
            # Try rank-1 term: val * e_i (x) e_j (x) e_k
            a = np.zeros(9, dtype=np.int8)
            b = np.zeros(9, dtype=np.int8)
            c = np.zeros(9, dtype=np.int8)
            a[i] = 1
            b[j] = 1
            c[k] = val
            
            score = 1  # at least hits this entry
            
            if score > best_score:
                best_score = score
                best_abc = (a.copy(), b.copy(), c.copy())
        
        # Also try: for each pair of nonzero entries sharing two indices
        # e.g., (i,j,k1) and (i,j,k2) -> a=e_i, b=e_j, c with c[k1]=v1, c[k2]=v2
        # This gives rank-1 terms hitting 2+ entries
        
        # Group nonzero entries by (i,j)
        from collections import defaultdict
        ij_groups = defaultdict(list)
        ik_groups = defaultdict(list)
        jk_groups = defaultdict(list)
        for pos in nz:
            i, j, k = pos
            ij_groups[(i, j)].append(k)
            ik_groups[(i, k)].append(j)
            jk_groups[(j, k)].append(i)
        
        # Try each (i,j) group
        for (i, j), ks in ij_groups.items():
            a = np.zeros(9, dtype=np.int8)
            b = np.zeros(9, dtype=np.int8)
            c = np.zeros(9, dtype=np.int8)
            a[i] = 1
            b[j] = 1
            for kk in ks:
                c[kk] = T_work[i, j, kk] % 3
            # Count how many entries this matches
            term = np.einsum('i,j,k->ijk', a, b, c) % 3
            score = np.sum((term % 3 != 0) & (term % 3 == T_work % 3))
            if score > best_score:
                best_score = score
                best_abc = (a.copy(), b.copy(), c.copy())
        
        for (i, k), js in ik_groups.items():
            a = np.zeros(9, dtype=np.int8)
            b = np.zeros(9, dtype=np.int8)
            c = np.zeros(9, dtype=np.int8)
            a[i] = 1
            c[k] = 1
            for jj in js:
                b[jj] = T_work[i, jj, k] % 3
            term = np.einsum('i,j,k->ijk', a, b, c) % 3
            score = np.sum((term % 3 != 0) & (term % 3 == T_work % 3))
            if score > best_score:
                best_score = score
                best_abc = (a.copy(), b.copy(), c.copy())
        
        for (j, k), is_ in jk_groups.items():
            a = np.zeros(9, dtype=np.int8)
            b = np.zeros(9, dtype=np.int8)
            c = np.zeros(9, dtype=np.int8)
            b[j] = 1
            c[k] = 1
            for ii in is_:
                a[ii] = T_work[ii, j, k] % 3
            term = np.einsum('i,j,k->ijk', a, b, c) % 3
            score = np.sum((term % 3 != 0) & (term % 3 == T_work % 3))
            if score > best_score:
                best_score = score
                best_abc = (a.copy(), b.copy(), c.copy())
        
        if best_abc is None:
            break
        
        a, b, c = best_abc
        term = np.einsum('i,j,k->ijk', a, b, c)
        T_work = (T_work - term) % 3
        rank += 1
        terms.append(best_abc)
        
        if verbose and rank % 5 == 0:
            remaining = np.sum(T_work % 3 != 0)
            print(f"  rank={rank}, remaining nonzero={remaining}, last_score={best_score}")
    
    remaining = np.sum(T_work % 3 != 0)
    return rank, terms, remaining


def f3_rank_via_matrix_multiplication_structure(T, verbose=True):
    """
    Use the KNOWN structure of matrix multiplication to build a decomposition.
    
    T_matmul encodes (AB)_{ru} = sum_s A_{rs} B_{su}.
    
    Over F_3, the standard algorithm uses 27 scalar multiplications 
    (one per (r,s,u) triple). So R_{F_3} <= 27 trivially.
    
    Strassen-like: can we do better over F_3?
    
    Key: Strassen's algorithm for 2x2 uses 7 multiplications. For 3x3,
    the best known over any field is 23.
    
    Over F_3 specifically: we have characteristic 3, so 3=0.
    This CHANGES the algebra. Identities that are impossible over R 
    might hold over F_3.
    
    Example: (a+b)^3 = a^3 + b^3 over F_3 (Freshman's dream).
    Frobenius endomorphism x -> x^3 is a field automorphism.
    
    For BILINEAR maps (matrix multiplication IS bilinear), the Frobenius
    doesn't directly help (it's not linear). But the fact that 
    char = dim = 3 is structurally significant.
    
    Compute: what is the minimum number of F_3-bilinear multiplications
    needed to compute 3x3 matrix product?
    
    This is exactly R_{F_3}(T_matmul).
    """
    # The standard decomposition (27 terms, one per r,s,u):
    # Term (r,s,u): a = e_{3r+s}, b = e_{3s+u}, c = e_{3r+u}
    # 27 rank-1 terms over ANY field.
    
    # Verify this works over F_3:
    T_check = np.zeros((9, 9, 9), dtype=np.int8)
    for r in range(3):
        for s in range(3):
            for u in range(3):
                a = np.zeros(9, dtype=np.int8)
                b = np.zeros(9, dtype=np.int8)
                c = np.zeros(9, dtype=np.int8)
                a[3*r + s] = 1
                b[3*s + u] = 1
                c[3*r + u] = 1
                T_check = (T_check + np.einsum('i,j,k->ijk', a, b, c)) % 3
    
    if verbose:
        print(f"  Standard 27-term decomposition correct over F_3: {np.array_equal(T_check, T)}")
    
    return 27


def rectangle_cover(verbose=True):
    """
    Compute gamma(S) — minimum rectangle cover of supp(T_matmul).
    
    S = {(3r+s, 3s+u, 3r+u) : r,s,u in {0,1,2}}
    
    A "rectangle" is A x B x C where A, B, C subset [9].
    We need to cover all 27 points of S with minimum number of rectangles,
    where each rectangle is contained in S.
    
    Key insight: each rectangle A x B x C that is a subset of S
    means: for all i in A, j in B, k in C: (i,j,k) in S.
    
    Let's enumerate the maximal rectangles in S.
    """
    # Build support set
    S = set()
    S_list = []
    for r in range(3):
        for s in range(3):
            for u in range(3):
                i, j, k = 3*r + s, 3*s + u, 3*r + u
                S.add((i, j, k))
                S_list.append((i, j, k))
    
    if verbose:
        print(f"  |S| = {len(S)}")
    
    # For each potential rectangle A x B x C (A, B, C subsets of {0..8}),
    # check if it's contained in S.
    # Enumerate maximal rectangles by checking which (j,k) pairs are valid for each i.
    
    # For each i, which (j,k) pairs are in S?
    from collections import defaultdict
    valid_jk = defaultdict(set)
    valid_ik = defaultdict(set)
    valid_ij = defaultdict(set)
    for (i, j, k) in S:
        valid_jk[i].add((j, k))
        valid_ik[j].add((i, k))
        valid_ij[k].add((i, j))
    
    if verbose:
        print("\n  Valid (j,k) per i:")
        for i in range(9):
            if i in valid_jk:
                print(f"    i={i}: {sorted(valid_jk[i])}")
    
    # A rectangle {i1,...} x {j1,...} x {k1,...} is in S iff
    # for ALL i in A, j in B, k in C: (i,j,k) in S.
    # Equivalently: B x C subset intersection of valid_jk[i] for i in A.
    
    # Find all maximal rectangles by checking intersections
    # Start: for each pair (i1, i2), what's the intersection of their valid_jk?
    
    # Enumerate ALL rectangles of size >= 1x1x2 or 1x2x1 or 2x1x1
    # (rectangles covering > 1 point)
    
    # Actually, let's just formulate as set cover IP and solve it.
    # Ground set: 27 points of S.
    # Sets: all rectangles A x B x C contained in S.
    # Objective: minimum number of sets to cover ground set.
    
    # Enumerate rectangles efficiently:
    # For each nonempty A subset {0..8}, compute intersection of valid_jk[i] for i in A.
    # Then for each partition of that intersection into B x C products...
    
    # This is getting complex. Let's use a cleaner approach.
    # 
    # Observation: T_matmul encodes matrix multiplication.
    # A rank-1 term in the decomposition IS a rectangle of size |supp(a)| x |supp(b)| x |supp(c)|.
    # So gamma(S) = minimum number of rank-1 support-coverings = support rank.
    # 
    # This is the BOOLEAN rank of the tensor (viewed as a {0,1}-tensor).
    # 
    # Boolean rank of T_matmul:
    # R_bool(T) = min R such that T = OR_{r=1}^R (a_r AND b_r AND c_r)
    # where a_r, b_r, c_r are {0,1}-vectors.
    #
    # Equivalently: minimum rectangles to cover the support.
    
    # Let's compute this via ILP.
    # Variables: x_rect in {0,1} for each maximal rectangle
    # Constraints: each point covered by at least one selected rectangle
    # Objective: minimize sum(x_rect)
    
    # First enumerate all maximal rectangles.
    # A rectangle is MAXIMAL if we can't add any element to A, B, or C
    # and still have A x B x C subset S.
    
    # Enumerate all rectangles by brute force on small subsets
    # Since |S| = 27 and indices in {0..8}, manageable.
    
    # Generate all rectangles: for A subset, B subset, C subset (nonempty),
    # check A x B x C subset S.
    # 2^9 * 2^9 * 2^9 = 2^27 ~ 134M — too many.
    
    # Better: enumerate rectangles from the structure.
    # Group by row index interpretation.
    # i = 3r + s means row i encodes (r, s).
    # j = 3s' + u means col j encodes (s', u).
    # k = 3r' + u' means output k encodes (r', u').
    # T[i,j,k] = 1 iff s = s' and r = r' and u = u'.
    
    # So (i,j,k) in S iff: writing i=(r,s), j=(s',u), k=(r',u'),
    # we need r=r', s=s', u=u'.
    # i.e., the SECOND digit of i = FIRST digit of j,
    #        the FIRST digit of i = FIRST digit of k,
    #        the SECOND digit of j = SECOND digit of k.
    
    # A rectangle A x B x C is in S iff:
    # For all (r,s) in A_decoded, (s',u) in B_decoded, (r',u') in C_decoded:
    #   s = s', r = r', u = u'.
    # This means:
    #   All elements of A_decoded have the SAME s-value (call it s0),
    #   All elements of B_decoded have FIRST digit = s0,
    #   All elements of B_decoded have SECOND digit in some set U,
    #   All elements of A_decoded have FIRST digit in some set R_set,
    #   All elements of C_decoded have FIRST digit in R_set,
    #   All elements of C_decoded have SECOND digit in U.
    
    # So a rectangle is determined by:
    #   s0 in {0,1,2} (the shared middle index)
    #   R_set subset {0,1,2} (the row indices)
    #   U_set subset {0,1,2} (the column indices)
    # And the rectangle is:
    #   A = {3r + s0 : r in R_set}
    #   B = {3*s0 + u : u in U_set}
    #   C = {3r + u : r in R_set, u in U_set}
    
    # Wait — that's not quite right for C. 
    # C needs elements (r', u') with r' in R_set and u' in U_set.
    # C = {3r + u : r in R_set, u in U_set} — this is ALL combinations.
    # |C| = |R_set| * |U_set|.
    
    # But check: does A x B x C subset S?
    # A element: i = 3r + s0 for some r in R_set
    # B element: j = 3*s0 + u for some u in U_set
    # C element: k = 3r' + u' for some r' in R_set, u' in U_set
    # For (i,j,k) in S: need 3r+s0, 3*s0+u, 3r+u — so k should be 3r+u.
    # But k = 3r'+u'. For this to equal 3r+u we need r'=r and u'=u.
    # So (i,j,k) in S iff r'=r and u'=u. But C contains ALL (r',u') combinations.
    # So we'd include (3r+s0, 3*s0+u, 3r'+u') where r'!=r — NOT in S.
    
    # So the rectangle A x B x C is NOT contained in S unless |R_set|=1 or |U_set|=1.
    # Because if |R_set|>1 and |U_set|>1, then C has cross-terms.
    
    # Wait, let me re-examine.
    # We need EVERY element of A x B x C to be in S.
    # Take a specific r in R_set and u in U_set. The triple 
    # (3r+s0, 3*s0+u, 3r+u) IS in S. Good.
    # But also take r1 != r2 both in R_set, u in U_set.
    # (3*r1+s0, 3*s0+u, 3*r2+u) — is this in S?
    # This needs r1=r2 (from the structure). NO. Not in S.
    
    # So... A x B x C is in S ONLY IF |R_set| = 1 OR |U_set| = 1 OR 
    # the C-set is carefully restricted.
    
    # Actually I got confused. Let me think again.
    # C doesn't have to be {3r+u : r in R_set, u in U_set}.
    # C is any subset of {0,...,8}. The constraint is that FOR ALL 
    # i in A, j in B, k in C: (i,j,k) in S.
    
    # So with A = {3r+s0 : r in R_set}, B = {3*s0+u : u in U_set}:
    # For each i=3r+s0 in A and j=3*s0+u in B, which k are valid?
    # (3r+s0, 3*s0+u, k) in S iff k = 3r+u.
    # So valid_k(i,j) = {3r+u} (a single element).
    
    # For A x B x C to be in S: C must be subset of 
    # INTERSECTION over (i,j) in A x B of valid_k(i,j).
    # = intersection over (r,u) in R_set x U_set of {3r+u}.
    # If |R_set| > 1 or |U_set| > 1, this intersection is EMPTY
    # (since 3r+u differs for different r or u).
    
    # WAIT. That means the ONLY rectangles in S with |A|>1, |B|>1 must have |C|=0.
    # And C must be nonempty. So...
    
    # The only valid rectangles are those where at least two of A, B, C are singletons,
    # OR they align perfectly.
    
    # Let me just check: what about A = {s0} (single i), B arbitrary, C arbitrary?
    # Fix i = 3r0 + s0 (so r=r0, s=s0 fixed).
    # Valid (j,k) for this i: (3*s0+u, 3*r0+u) for u in {0,1,2}.
    # So j determines k: k = 3*r0 + (j - 3*s0) = 3*r0 + (j mod 3).
    # Rectangle: {i} x B x C. For this to work: for each j in B, 
    # the unique valid k must be in C. So C = {3*r0 + (j mod 3) : j in B, j/3 = s0}.
    # Actually j must have first digit s0, so j in {3*s0, 3*s0+1, 3*s0+2}.
    # B subset {3*s0, 3*s0+1, 3*s0+2}, |B| <= 3.
    # C = {3*r0 + u : 3*s0+u in B} = corresponding u-shifted.
    # |C| = |B|.
    # Rectangle size: 1 x |B| x |B|, covering |B| points.
    # Max: 1 x 3 x 3 = 3 points covered.
    
    # Similarly for B singleton or C singleton.
    
    # B singleton: j = 3*s0+u0. Valid (i,k): i=3r+s0, k=3r+u0 for r in {0,1,2}.
    # Rectangle: A x {j} x C. A = {3r+s0 : r in R_set}, C = {3r+u0 : r in R_set}.
    # Size |R_set| x 1 x |R_set|. Max 3 x 1 x 3 = 3 points.
    
    # C singleton: k = 3*r0+u0. Valid (i,j): i=3*r0+s, j=3s+u0 for s in {0,1,2}.
    # Rectangle: A x B x {k}. A = {3*r0+s : s in S_set}, B = {3s+u0 : s in S_set}.
    # Size |S_set| x |S_set| x 1. Max 3 x 3 x 1 = 3 points.
    
    # SO: every maximal rectangle covers at most 3 points!
    # And |S| = 27. Therefore gamma(S) >= 27/3 = 9.
    # And gamma(S) <= 27 (trivially).
    
    # Can we cover all 27 with 9 rectangles of size 3?
    # Partition by s0: s0 in {0,1,2}, for each s0, 9 points.
    # Within s0: points (3r+s0, 3*s0+u, 3r+u) for r,u in {0,1,2}.
    # Fix r=r0: 3 points (3*r0+s0, 3*s0+u, 3*r0+u) for u in {0,1,2}.
    # This is a 1x3x3 rectangle (A={3*r0+s0}, B={3*s0,3*s0+1,3*s0+2}, C={3*r0,3*r0+1,3*r0+2}).
    # Wait: but we showed A x B x C must have ALL combos in S.
    # Check: (3*r0+s0, 3*s0+u, k) in S iff k=3*r0+u. 
    # So C must be exactly {3*r0+u : u in {0,1,2}} = {3*r0, 3*r0+1, 3*r0+2}.
    # And for each j=3*s0+u in B, the valid k is 3*r0+u. Since ALL such k are in C, YES.
    # This rectangle IS contained in S and covers 3 points.
    
    # 3 values of s0 x 3 values of r0 = 9 rectangles, each covering 3 points.
    # 9 x 3 = 27 = |S|. And they partition S (each point in exactly one).
    
    # So gamma(S) <= 9.
    # And gamma(S) >= 9 (since max rectangle size = 3).
    # Therefore gamma(S) = 9.
    
    if verbose:
        print("\n  RECTANGLE COVER ANALYSIS")
        print("  " + "="*60)
        print(f"  |S| = 27")
        print(f"  Max rectangle size in S = 3")
        print(f"  Therefore gamma(S) >= ceil(27/3) = 9")
        print()
        print("  Partition into 9 rectangles of size 3:")
        
        for s0 in range(3):
            for r0 in range(3):
                A = [3*r0 + s0]
                B = [3*s0 + u for u in range(3)]
                C = [3*r0 + u for u in range(3)]
                points = [(3*r0+s0, 3*s0+u, 3*r0+u) for u in range(3)]
                print(f"    s0={s0}, r0={r0}: A={A} x B={B} x C={C} -> {points}")
        
        # Verify partition
        all_covered = set()
        for s0 in range(3):
            for r0 in range(3):
                for u in range(3):
                    all_covered.add((3*r0+s0, 3*s0+u, 3*r0+u))
        
        print(f"\n  Total points covered: {len(all_covered)}")
        print(f"  Equals S: {all_covered == S}")
        print(f"\n  gamma(S) = 9 (EXACT)")
        print(f"  => R(T_matmul) >= 9 from rectangle cover")
        print(f"  (This is just the multilinear rank bound — not stronger)")
    
    return 9


def main():
    print("="*70)
    print("F_3 TENSOR RANK OF T_matmul(3x3)")
    print("="*70)
    
    T = build_T_matmul()
    print(f"\nT_matmul built: shape {T.shape}, nnz={np.sum(T != 0)}")
    print(f"Entries: all in {{0, 1}} mod 3: {set(T.flatten())}")
    
    # §1: Multilinear rank
    print("\n§1  MULTILINEAR RANK OVER F_3")
    print("-"*70)
    mlr = multilinear_rank_f3(T)
    print(f"  (r_A, r_B, r_C) = {mlr}")
    print(f"  Lower bound from multilinear rank: R >= {max(mlr)}")
    
    # §2: Flattening ranks
    print("\n§2  FLATTENING RANKS OVER F_3")
    print("-"*70)
    flat = systematic_f3_rank_search(T)
    for key, val in flat.items():
        print(f"  {key}: {val}")
    
    # §3: Substitution method
    print("\n§3  SUBSTITUTION METHOD OVER F_3")
    print("-"*70)
    sub_rank = substitution_lower_bound(T)
    print(f"  dim(span{{L_0, ..., L_8}}) over F_3 = {sub_rank}")
    print(f"  Lower bound: R >= {sub_rank}")
    
    # §4: Algebra structure
    print("\n§4  ALGEBRA STRUCTURE OVER F_3")
    print("-"*70)
    alg = commutative_algebra_bound_f3(T)
    for key, val in alg.items():
        print(f"  {key}: {val}")
    
    # §5: Strassen equations check
    print("\n§5  MATRIX UNIT RELATIONS OVER F_3")
    print("-"*70)
    rel = strassen_equations_f3(T)
    print(f"  Total relations checked: {rel['total_relations']}")
    print(f"  Violations: {rel['violations']}")
    print(f"  Matrix algebra M_3(F_3) verified: {rel['violations'] == 0}")
    
    # §6: Standard decomposition verification
    print("\n§6  STANDARD DECOMPOSITION (27 TERMS) OVER F_3")
    print("-"*70)
    f3_rank_via_matrix_multiplication_structure(T)
    
    # §7: Greedy upper bound
    print("\n§7  GREEDY PEELING UPPER BOUND OVER F_3")
    print("-"*70)
    greedy_rank, terms, remaining = f3_rank_via_greedy_peeling(T)
    print(f"  Greedy rank (upper bound): {greedy_rank}")
    print(f"  Remaining nonzero entries: {remaining}")
    
    # §8: Rectangle cover
    print("\n§8  RECTANGLE COVER gamma(S)")
    print("-"*70)
    gamma = rectangle_cover()
    
    # §9: Random search for low-rank decompositions over F_3
    print("\n§9  RANDOM SEARCH FOR LOW-RANK DECOMPOSITIONS OVER F_3")
    print("-"*70)
    
    # Try R = 19, 20, 21, 22, 23 with random sampling
    for R_test in [19, 20, 21, 22, 23]:
        t0 = time.time()
        found, decomp = check_rank_r_f3(T, R_test, max_attempts=50000, verbose=False)
        dt = time.time() - t0
        status = "FOUND" if found else "not found"
        print(f"  R={R_test}: {status} ({dt:.1f}s, 50k attempts)")
        if found:
            print(f"    ** R_{{F_3}}(T_matmul) <= {R_test} **")
            break
    
    # §10: Characteristic-3 specific structure
    print("\n§10 CHARACTERISTIC-3 SPECIFIC ANALYSIS")
    print("-"*70)
    
    # Over F_3: the Frobenius endomorphism x -> x^3 = x (on F_3).
    # So Frobenius is the IDENTITY on F_3. This means:
    # The Frobenius-semilinear maps are just linear maps.
    # No extra structure from Frobenius.
    
    # But: over F_3^n (extension fields), Frobenius is nontrivial.
    # Could use F_9, F_27, F_81 to get different decompositions.
    
    # Over F_9 = F_3[x]/(x^2+1):
    # rank_{F_9} <= rank_{F_3} since F_9 contains F_3.
    # But rank_{F_9} could be STRICTLY less.
    
    print("  Frobenius on F_3: x -> x^3 = x (identity)")
    print("  No extra structure from base field Frobenius")
    print()
    print("  Extension field possibilities:")
    print("    F_9:  rank_{F_9}(T) <= rank_{F_3}(T)")
    print("    F_27: rank_{F_27}(T) <= rank_{F_3}(T)")
    print("    rank_{F_3}(T) <= rank_R(T)")
    print()
    
    # The critical computation: Strassen's 2x2 algorithm uses 7 mults.
    # Over F_2, 2x2 matmul has rank 7 (same as over R).
    # Over large fields, rank can drop via algebraic identities.
    # For 3x3 over F_3: unknown. Known: 19 <= R_R(T) <= 23.
    # R_{F_3} could differ.
    
    # Key theorem (Bürgisser-Clausen-Shokrollahi):
    # For matrix multiplication tensors over algebraically closed fields,
    # rank is the same as over any infinite field extension.
    # But F_3 is NOT algebraically closed. So R_{F_3} could be > R_{\bar{F_3}}.
    
    print("  Key: F_3 is NOT algebraically closed")
    print("  R_{F_3}(T) >= R_{\\bar{F_3}}(T) >= R_C(T)")
    print("  Rank over F_3 could be HIGHER than over C or R")
    print("  This means: if R_{F_3} = k, then R_R >= ??? (no direct implication)")
    print()
    print("  CORRECTION: The implication goes:")
    print("    R_{F_3}(T) is rank of the F_3-FORM of T")
    print("    R_R(T) is rank of the R-FORM of T")
    print("    They are the SAME tensor (entries 0,1)")
    print("    R_{F_3}(T) >= R_R(T) is FALSE in general")
    print("    R_{F_3}(T) <= R_R(T) is ALSO not guaranteed")
    print("    They are INDEPENDENT quantities over different fields")
    print()
    print("  What IS true:")
    print("    R_{\\bar{F_3}}(T) <= R_{F_3}(T)  (larger field can only help)")
    print("    R_C(T) <= R_R(T)  (similarly)")
    print("    For 0/1 tensors: R_{F_p}(T) and R_R(T) are NOT directly comparable")
    
    # §11: Summary
    print("\n" + "="*70)
    print("SUMMARY")
    print("="*70)
    print(f"  Multilinear rank over F_3: {mlr}")
    print(f"  Substitution rank: {sub_rank}")
    print(f"  Algebra dimension (deg 2): {alg['algebra_dim_deg2']}")
    print(f"  Algebra dimension (deg 3): {alg['algebra_dim_deg3']}")
    print(f"  Matrix unit relations: {'VERIFIED' if rel['violations']==0 else 'FAILED'}")
    print(f"  Greedy upper bound: {greedy_rank}")
    print(f"  Rectangle cover gamma(S): {gamma}")
    print(f"  Standard decomposition: 27 terms")
    print(f"\n  Key finding: gamma(S) = {gamma}")
    print(f"  Max rectangle in supp(T_matmul) covers only 3 points")
    print(f"  This means EVERY rank-1 term touches at most 3 of 27 support entries")
    print(f"  => Boolean tensor rank = support rank = 9")
    print(f"  => Rectangle cover gives R >= 9 (matches multilinear rank, not new)")


if __name__ == '__main__':
    main()
