"""
ade3x3_step41_stabilizer_classification.py

Stabilizer Subgroup Classification for CXC (50 orbits) and CXXC (2744 orbits).

For each orbit, classify the stabilizer subgroup by:
  1. Order (= 216 / orbit_size, already known)
  2. Element orders (lcm of component permutation orders in S3×S3×S3)
  3. Abelian check (pairwise commutativity)
  4. Isomorphism type (human-readable name)

Structural constraint: elements of S3×S3×S3 have orders in {1,2,3,6}.
Therefore stabilizer subgroups in CXXC (sizes {1,2,4,8}) are:
  - Order 1: Trivial
  - Order 2: Z2
  - Order 4: Z2xZ2 (no order-4 elements possible)
  - Order 8: (Z2)^3  (no order-4/8 elements possible; abelian group of exponent 2)

CXC orbits have sizes dividing 216; we classify whatever appears.

Output columns:
  schema | orbit_id | rep_config_id | orbit_size | stabilizer_order
  | stabilizer_type | is_abelian | element_orders | generator_action_ids

Provenance: [EXACT_DERIVED]
"""

import csv
import json
from pathlib import Path
from datetime import datetime
from collections import defaultdict, Counter
from itertools import product as iproduct

EXPORTS = Path('outputs/exports')

# ──────────────────────────────────────────────────────────────────────────────
# Group definition
# ──────────────────────────────────────────────────────────────────────────────

S3 = [(0,1,2),(0,2,1),(1,0,2),(1,2,0),(2,0,1),(2,1,0)]
IDENTITY = (0,1,2)

ACTIONS = [(p1,p2,p3) for p1 in S3 for p2 in S3 for p3 in S3]
# action_id → (p1,p2,p3)
# Verification: identity is ACTIONS[0]
assert ACTIONS[0] == ((0,1,2),(0,1,2),(0,1,2))

def perm_compose(p: tuple, q: tuple) -> tuple:
    """Compose permutations: apply q first, then p; returns p∘q."""
    return tuple(p[q[i]] for i in range(3))

def action_compose(a: tuple, b: tuple) -> tuple:
    """Compose group elements (p1,p2,p3) * (q1,q2,q3) = (p1∘q1, p2∘q2, p3∘q3)."""
    return (perm_compose(a[0],b[0]), perm_compose(a[1],b[1]), perm_compose(a[2],b[2]))

def perm_order(p: tuple) -> int:
    """Order of a permutation in S3."""
    if p == (0,1,2): return 1
    if p[p[p[0]]] == 0 and p[p[p[1]]] == 1 and p[p[p[2]]] == 2:
        return 3 if p[0] != 0 else 1  # could be 3-cycle
    # check 2-cycle: p != id and p∘p = id
    if tuple(p[p[i]] for i in range(3)) == (0,1,2):
        return 2
    return 3  # 3-cycle

def _perm_order_exact(p):
    """Exact order by repeated application."""
    q = p
    for k in range(1, 7):
        if q == (0,1,2):
            return k
        q = perm_compose(p, q)
    raise ValueError(f"Order > 6 for {p}")

def element_order(a: tuple) -> int:
    """Order of group element (p1,p2,p3) = lcm of component orders."""
    from math import gcd
    def lcm2(x,y): return x*y//gcd(x,y)
    o1 = _perm_order_exact(a[0])
    o2 = _perm_order_exact(a[1])
    o3 = _perm_order_exact(a[2])
    return lcm2(lcm2(o1,o2),o3)

# ──────────────────────────────────────────────────────────────────────────────
# Stabilizer computation
# ──────────────────────────────────────────────────────────────────────────────

def _find_stabilizer_ids(rep: int, act_fn) -> list[int]:
    """Return sorted list of action indices that fix rep."""
    return sorted(aid for aid, a in enumerate(ACTIONS) if act_fn(rep, a) == rep)

# ──────────────────────────────────────────────────────────────────────────────
# Subgroup classification
# ──────────────────────────────────────────────────────────────────────────────

def classify_subgroup(stab_ids: list[int]) -> dict:
    """
    Given stabilizer action indices, classify the subgroup.
    Returns: {stabilizer_type, is_abelian, element_orders, generator_action_ids}
    """
    size = len(stab_ids)
    elements = [ACTIONS[aid] for aid in stab_ids]
    identity = ACTIONS[0]

    # Compute element orders
    orders = [element_order(e) for e in elements]
    order_counter = Counter(orders)

    # Check abelian
    is_abelian = True
    for i, a in enumerate(elements):
        for j, b in enumerate(elements):
            if j <= i: continue
            ab = action_compose(a, b)
            ba = action_compose(b, a)
            if ab != ba:
                is_abelian = False
                break
        if not is_abelian:
            break

    # Find minimal generators (greedy: add elements until group is generated)
    generator_ids = _find_generators(stab_ids, elements)

    # Classify type
    stab_type = _classify_type(size, order_counter, is_abelian)

    return {
        'stabilizer_type': stab_type,
        'is_abelian': is_abelian,
        'element_orders': dict(sorted(order_counter.items())),
        'generator_action_ids': generator_ids,
    }


def _group_generated_by(gens: list[tuple], all_elements: list[tuple]) -> set[tuple]:
    """Compute the subgroup generated by a set of elements (subset of all_elements)."""
    gen_set = set(gens)
    gen_set.add(ACTIONS[0])  # always include identity
    prev_size = 0
    while len(gen_set) != prev_size:
        prev_size = len(gen_set)
        new = set()
        for a in gen_set:
            for b in gen_set:
                c = action_compose(a, b)
                if c in set(all_elements):
                    new.add(c)
        gen_set |= new
    return gen_set


def _find_generators(stab_ids: list[int], elements: list[tuple]) -> list[int]:
    """Find a minimal generating set (greedy)."""
    if len(stab_ids) == 1:  # just identity
        return []
    elem_set = set(elements)
    generated = {ACTIONS[0]}  # start with identity
    gens = []
    non_identity = [(aid, e) for aid, e in zip(stab_ids, elements) if e != ACTIONS[0]]
    # Sort by element order descending (prefer higher-order generators)
    non_identity.sort(key=lambda x: -element_order(x[1]))
    for aid, e in non_identity:
        if e not in generated:
            gens.append(aid)
            # expand generated set
            new_gens = [ACTIONS[g] for g in gens]
            generated = _group_generated_by(new_gens, elements)
            if len(generated) == len(elements):
                break
    return gens


def _classify_type(size: int, order_counter: Counter, is_abelian: bool) -> str:
    """Map (size, order histogram, abelian?) to isomorphism type name."""
    if size == 1:
        return "Trivial"
    if size == 2:
        return "Z2"
    if size == 3:
        return "Z3"
    if size == 4:
        # In S3³, max element order = 6. A group of order 4 can't have order-4 elements.
        # So it's either Z4 or Z2×Z2. Since no order-4 elements: Z2×Z2
        if order_counter.get(4, 0) > 0:
            return "Z4"
        return "Z2xZ2"
    if size == 6:
        if is_abelian:
            # Z6 or Z3×Z2. Z6 has an element of order 6. Z3×Z2 ≅ Z6.
            return "Z6" if order_counter.get(6, 0) > 0 else "Z2xZ3"
        else:
            return "S3"
    if size == 8:
        # In S3³, no order-4 or order-8 elements. All elements of order ≤ 3.
        # Order-8 group with all elements of order ≤ 2: (Z2)^3
        # Order-8 group with order-3 elements? Impossible (Lagrange: 3 must divide 8).
        if all(o <= 2 for o in order_counter.keys()):
            return "(Z2)^3"
        # Shouldn't happen in S3³
        return f"Unknown_ord8_orders={dict(order_counter)}"
    if size == 12:
        if is_abelian:
            if order_counter.get(6, 0) > 0:
                return "Z6xZ2"  # or Z12, but no order-12 in S3³
            return "Z2xZ2xZ3"
        else:
            # Non-abelian order 12: A4, D6
            if order_counter.get(3, 0) == 8:
                return "A4"
            return "D6"
    if size == 18:
        # Various options
        if is_abelian:
            return "Z2xZ3xZ3" if order_counter.get(6, 0) == 0 else "Z6xZ3"
        return "D9_or_S3xZ3"
    if size == 24:
        return "S4_or_other_ord24"
    if size == 27:
        if is_abelian:
            if max(order_counter.keys()) == 3:
                return "(Z3)^3"
            return "Z9xZ3"
        return "NonAbelian_ord27"
    if size == 36:
        return "order36_subgroup"
    if size == 54:
        return "order54_subgroup"
    if size == 72:
        return "order72_subgroup"
    if size == 108:
        return "order108_subgroup"
    if size == 216:
        return "S3xS3xS3"
    return f"Unknown_ord{size}"

# ──────────────────────────────────────────────────────────────────────────────
# Action functions
# ──────────────────────────────────────────────────────────────────────────────

def _act_CXC(cfg, act):
    c1=cfg//(81*9); rem=cfg%(81*9); x=rem//9; c2=rem%9
    r1,u1=divmod(c1,3); r2,s=divmod(x//9,3); t,u2=divmod(x%9,3); r3,u3=divmod(c2,3)
    return ((3*act[0][r1]+act[2][u1])*81+9*(3*act[0][r2]+act[1][s]) +
            (3*act[1][t]+act[2][u2]))*9+(3*act[0][r3]+act[2][u3])

def _act_CXXC(cfg, act):
    c2=cfg%9; rem=cfg//9; x2=rem%81; rem//=81; x1=rem%81; c1=rem//81
    r1,u1=divmod(c1,3); r2,s2=divmod(x1//9,3); t2,u2=divmod(x1%9,3)
    r4,s4=divmod(x2//9,3); t4,u4=divmod(x2%9,3); r3,u3=divmod(c2,3)
    c1n=3*act[0][r1]+act[2][u1]
    x1n=9*(3*act[0][r2]+act[1][s2])+(3*act[1][t2]+act[2][u2])
    x2n=9*(3*act[0][r4]+act[1][s4])+(3*act[1][t4]+act[2][u4])
    c2n=3*act[0][r3]+act[2][u3]
    return ((c1n*81+x1n)*81+x2n)*9+c2n

# ──────────────────────────────────────────────────────────────────────────────
# Orbit enumeration
# ──────────────────────────────────────────────────────────────────────────────

def enumerate_orbits(n: int, act_fn) -> list[dict]:
    """Enumerate orbits with stabilizer element IDs."""
    min_r = [0] * n
    for cfg in range(n):
        m = cfg
        for a in ACTIONS:
            v = act_fn(cfg, a)
            if v < m:
                m = v
        min_r[cfg] = m
    groups = defaultdict(list)
    for cfg in range(n):
        groups[min_r[cfg]].append(cfg)
    orbits = []
    for oid, (rep, members) in enumerate(sorted(groups.items())):
        stab_ids = _find_stabilizer_ids(rep, act_fn)
        orbits.append({
            'orbit_id': oid,
            'rep_config_id': rep,
            'orbit_size': len(members),
            'stabilizer_size': len(stab_ids),
            'stabilizer_ids': stab_ids,
        })
    return orbits

# ──────────────────────────────────────────────────────────────────────────────
# Writers
# ──────────────────────────────────────────────────────────────────────────────

FIELDS = [
    'schema', 'orbit_id', 'rep_config_id', 'orbit_size',
    'stabilizer_order', 'stabilizer_type', 'is_abelian',
    'element_orders', 'generator_action_ids',
]

def write_csv(all_rows: list[dict], path: Path):
    with open(path, 'w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(all_rows)
    print(f"  Wrote {len(all_rows)} rows → {path}")


def write_markdown(all_rows: list[dict], stats: dict, path: Path):
    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    lines = [
        "# Stabilizer Subgroup Classification: CXC and CXXC",
        "",
        f"Generated: {ts}",
        "",
        "[EXACT_DERIVED]",
        "",
        "## Background",
        "",
        "The ambient group is S3×S3×S3 (order 216). Elements have orders in {1,2,3,6}.",
        "For a given orbit with representative `r`, the stabilizer is:",
        "  Stab(r) = {g ∈ G : g·r = r}",
        "which is a subgroup of G by the orbit-stabilizer theorem.",
        "",
        "Isomorphism types are determined by:",
        "  - Subgroup order (= 216 / orbit_size)",
        "  - Element order histogram",
        "  - Abelian vs non-abelian",
        "",
        "**Constraint:** S3×S3×S3 has no elements of order 4, 5, 7, 8, ... (only 1,2,3,6).",
        "This rules out Z4, Q8, D4, Z8, etc. as stabilizer types.",
        "",
    ]

    for schema in ['CXC', 'CXXC']:
        schema_rows = [r for r in all_rows if r['schema'] == schema]
        n = len(schema_rows)
        type_counts = Counter(r['stabilizer_type'] for r in schema_rows)
        order_counts = Counter(r['stabilizer_order'] for r in schema_rows)

        lines += [
            f"## {schema} Stabilizer Classification",
            "",
            f"**Orbit count:** {n}",
            "",
            "### Stabilizer Type Distribution",
            "",
            "| Stabilizer Type | Orbit Count | Fraction |",
            "|-----------------|-------------|----------|",
        ]
        for stype in sorted(type_counts.keys(), key=lambda t: (
            int(next(r['stabilizer_order'] for r in schema_rows if r['stabilizer_type']==t)), t
        )):
            cnt = type_counts[stype]
            lines.append(f"| {stype} | {cnt} | {cnt/n:.4f} |")

        lines += [
            "",
            "### Stabilizer Order Distribution",
            "",
            "| Stabilizer Order | Orbit Count | Orbit Size | Fraction of Orbits |",
            "|------------------|-------------|------------|---------------------|",
        ]
        for order in sorted(order_counts.keys()):
            cnt = order_counts[order]
            orb_size = 216 // order
            lines.append(f"| {order} | {cnt} | {orb_size} | {cnt/n:.4f} |")

        lines += [
            "",
            "### Full Table",
            "",
            "| orbit_id | rep_config_id | orbit_size | stab_order | type | is_abelian | element_orders |",
            "|----------|--------------|------------|------------|------|------------|----------------|",
        ]
        for row in schema_rows:
            lines.append(
                f"| {row['orbit_id']} | {row['rep_config_id']} | {row['orbit_size']} "
                f"| {row['stabilizer_order']} | {row['stabilizer_type']} "
                f"| {row['is_abelian']} | {row['element_orders']} |"
            )

    lines += ["", "---", "*Generated by ade3x3_step41_stabilizer_classification.py*", ""]
    with open(path, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))
    print(f"  Wrote markdown → {path}")

# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def main():
    print("=== Stabilizer Subgroup Classification ===")
    print()

    all_rows = []

    # ── CXC ──────────────────────────────────────────────────────────────────
    print("Computing CXC orbits and stabilizers (6,561 configs)...")
    cxc_orbits = enumerate_orbits(9*81*9, _act_CXC)
    assert len(cxc_orbits) == 50, f"CXC: {len(cxc_orbits)} orbits"
    print(f"  50 CXC orbits ✓")

    print("  Classifying CXC stabilizers...")
    cxc_stats = Counter()
    for orb in cxc_orbits:
        info = classify_subgroup(orb['stabilizer_ids'])
        cxc_stats[info['stabilizer_type']] += 1
        all_rows.append({
            'schema': 'CXC',
            'orbit_id': orb['orbit_id'],
            'rep_config_id': orb['rep_config_id'],
            'orbit_size': orb['orbit_size'],
            'stabilizer_order': orb['stabilizer_size'],
            'stabilizer_type': info['stabilizer_type'],
            'is_abelian': info['is_abelian'],
            'element_orders': json.dumps(info['element_orders']),
            'generator_action_ids': json.dumps(info['generator_action_ids']),
        })
    print(f"  CXC type distribution: {dict(cxc_stats)}")
    print()

    # ── CXXC ─────────────────────────────────────────────────────────────────
    print("Computing CXXC orbits and stabilizers (531,441 configs)...")
    print("  [This may take a few minutes — 531,441 × 216 = 114M group operations]")
    cxxc_orbits = enumerate_orbits(531_441, _act_CXXC)
    assert len(cxxc_orbits) == 2744, f"CXXC: {len(cxxc_orbits)} orbits"
    print(f"  2744 CXXC orbits ✓")

    print("  Classifying CXXC stabilizers...")
    cxxc_stats = Counter()
    for orb in cxxc_orbits:
        info = classify_subgroup(orb['stabilizer_ids'])
        cxxc_stats[info['stabilizer_type']] += 1
        all_rows.append({
            'schema': 'CXXC',
            'orbit_id': orb['orbit_id'],
            'rep_config_id': orb['rep_config_id'],
            'orbit_size': orb['orbit_size'],
            'stabilizer_order': orb['stabilizer_size'],
            'stabilizer_type': info['stabilizer_type'],
            'is_abelian': info['is_abelian'],
            'element_orders': json.dumps(info['element_orders']),
            'generator_action_ids': json.dumps(info['generator_action_ids']),
        })
    print(f"  CXXC type distribution: {dict(cxxc_stats)}")
    print()

    stats = {'CXC': cxc_stats, 'CXXC': cxxc_stats}

    print("Writing outputs...")
    csv_path = EXPORTS / 'stabilizer_classification.csv'
    md_path  = EXPORTS / 'stabilizer_classification.md'
    write_csv(all_rows, csv_path)
    write_markdown(all_rows, stats, md_path)

    print()
    print("=== Done ===")
    print(f"Total rows: {len(all_rows)} (50 CXC + 2744 CXXC)")


if __name__ == '__main__':
    import os
    os.chdir(Path(__file__).resolve().parents[3])
    main()
